#!/bin/bash

echo "Starting tree generation."
time python3 ReverseCollatz.py > ReverseCollatz.dot
echo "Finished generating tree."
echo "-------------------------"
echo "Starting graphing."
time dot -Tpdf ReverseCollatz.dot -o ReverseCollatz.pdf
echo "Finished graphing tree."
