#!/bin/bash

echo "Starting tree generation."
time python3 NormalCollatz.py > NormalCollatz.gv
echo "Finished generating tree."
echo "-------------------------"
echo "Starting graphing."
time dot -Tpdf NormalCollatz.gv -o NormalCollatz.pdf
echo "Finished graphing tree."
