#!/bin/bash

echo "Starting tree generation."
time python3 ReverseCollatz.py > ReverseCollatz.gv
echo "Finished generating tree."
echo "-------------------------"
echo "Starting graphing."
time dot -Tpdf ReverseCollatz.gv -o ReverseCollatz.pdf
echo "Finished graphing tree."
